python client/test_client.py "How much does a Macbook Air Cost?"
python client/test_client.py "Where can i get a drink of water?"
python client/test_client.py "Who is Don Cornero?"
python client/test_client.py "How are you feeling today?"
python client/test_client.py "What does a cake recipe consist of?"
python client/test_client.py "When does the move release in theaters?"
python client/test_client.py "Where is the Sears Tower?"
python client/test_client.py "Who is Iron Man?"
python client/test_client.py "What is the powerhouse of the cell?"
python client/test_client.py "What inspired Micheal Jordan?"

